name: build
on:
  push:
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
env:
  LINK: 'https://ziglang.org/builds/zig-linux-x86_64-0.14.0-dev.2851+b074fb7dd.tar.xz'
  SRC: 'ce.c buffer.c dirlist.c editor.c game.c hist.c proc.c syntax.c term.c utf8.c'
  CFLAGS: '-target aarch64-linux-musl -fstrip -fno-PIC -ffunction-sections -fdata-sections -fno-PIE -fllvm -flibllvm -flto -library c'
  
jobs:
  CreatTag:
    runs-on: ubuntu-latest
    steps:
    - if: ENV.env == 1
      uses: actions/checkout@v4
    - name: Create a new tag
      if: ENV.env == 1
      run: |
        TAG_NAME="nightly"
        git tag $TAG_NAME
        git push origin $TAG_NAME
  help:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: HELP
      run: |
        mkdir .zig && cd .zig
        curl -o zig.tar.xz $LINK
        tar -xf zig.tar.xz && rm zig.tar.xz
        mv * zig && cd zig && export PATH=$PATH:$PWD
        cd ../..
        zig build-exe --help        
  kryo_Fast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup llvm
      run: |
        curl -o llvm.sh https://apt.llvm.org/llvm.sh
        sudo chmod 777 llvm.sh
        sudo ./llvm.sh 19 all
    - name: Build
      run: |
        mkdir .zig && cd .zig
        curl -o zig.tar.xz $LINK
        tar -xf zig.tar.xz && rm zig.tar.xz
        mv * zig && cd zig && export PATH=$PATH:$PWD
        cd ../..
        zig build-exe $CFLAGS -mcpu="kryo" -O ReleaseFast --zig-lib-dir "$PWD/.zig/zig/lib" "$(SRC)"
    - name: Pack output
      run: |
        mv zig-out nightly
        7z a kryo_fast.7z nightly/bin/flow
        tar -cJf kryo_fast.tar.xz nightly/bin/flow
        tar -cf kryo_fast.tar nightly/bin/flow
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        make_latest: true
        files: |
          kryo_fast.tar
          kryo_fast.tar.xz
          kryo_fast.7z
    - name: Check zig binary size
      run: |
        ls -lh nightly/bin
        ls -l nightly/bin
        
  kryo_Small:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup llvm
      run: |
        curl -o llvm.sh https://apt.llvm.org/llvm.sh
        sudo chmod 777 llvm.sh
        sudo ./llvm.sh 19 all
    - name: Build
      run: |
        mkdir .zig && cd .zig
        curl -o zig.tar.xz $LINK
        tar -xf zig.tar.xz && rm zig.tar.xz
        mv * zig && cd zig && export PATH=$PATH:$PWD
        cd ../..
        zig build-exe $CFLAGS -mcpu="kryo" -O ReleaseSmall --zig-lib-dir "$PWD/.zig/zig/lib" "$(SRC)"
    - name: Pack output
      run: |
        mv zig-out nightly
        7z a kryo_small.7z nightly/bin/flow
        tar -cJf kryo_small.tar.xz nightly/bin/flow
        tar -cf kryo_small.tar nightly/bin/flow
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        make_latest: true
        files: |
          kryo_small.tar
          kryo_small.tar.xz
          kryo_small.7z
    - name: Check zig binary size
      run: |
        ls -lh nightly/bin/
        ls -l nightly/bin/





  x1c_Fast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup llvm
      run: |
        curl -o llvm.sh https://apt.llvm.org/llvm.sh
        sudo chmod 777 llvm.sh
        sudo ./llvm.sh 19 all
    - name: Build
      run: |
        mkdir .zig && cd .zig
        curl -o zig.tar.xz $LINK
        tar -xf zig.tar.xz && rm zig.tar.xz
        mv * zig && cd zig && export PATH=$PATH:$PWD
        cd ../..
        zig build-exe $CFLAGS -mcpu="cortex_x1c" -O ReleaseFast --zig-lib-dir "$PWD/.zig/zig/lib" "$(SRC)"
    - name: Pack output
      run: |
        mv zig-out nightly
        7z a x1c_fast.7z nightly/bin/flow
        tar -cJf x1c_fast.tar.xz nightly/bin/flow
        tar -cf x1c_fast.tar nightly/bin/flow
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        make_latest: true
        files: |
          x1c_fast.tar
          x1c_fast.tar.xz
          x1c_fast.7z
    - name: Check zig binary size
      run: |
        ls -lh nightly/bin/
        ls -l nightly/bin/
        
  x1c_Small:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup llvm
      run: |
        curl -o llvm.sh https://apt.llvm.org/llvm.sh
        sudo chmod 777 llvm.sh
        sudo ./llvm.sh 19 all
    - name: Build
      run: |
        mkdir .zig && cd .zig
        curl -o zig.tar.xz $LINK
        tar -xf zig.tar.xz && rm zig.tar.xz
        mv * zig && cd zig && export PATH=$PATH:$PWD
        cd ../..
        zig build-exe $CFLAGS -mcpu="cortex_x1c" -O ReleaseSmall --zig-lib-dir "$PWD/.zig/zig/lib" "$(SRC)"
    - name: Pack output
      run: |
        mv zig-out nightly
        7z a x1c_small.7z nightly/bin/flow
        tar -cJf x1c_small.tar.xz nightly/bin/flow
        tar -cf x1c_small.tar nightly/bin/flow
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        make_latest: true
        files: |
          x1c_small.tar
          x1c_small.tar.xz
          x1c_small.7z
    - name: Check zig binary size
      run: |
        ls -lh nightly/bin/
        ls -l nightly/bin/





  baseline_Fast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup llvm
      run: |
        curl -o llvm.sh https://apt.llvm.org/llvm.sh
        sudo chmod 777 llvm.sh
        sudo ./llvm.sh 19 all
    - name: Build
      run: |
        mkdir .zig && cd .zig
        curl -o zig.tar.xz $LINK
        tar -xf zig.tar.xz && rm zig.tar.xz
        mv * zig && cd zig && export PATH=$PATH:$PWD
        cd ../..
        zig build-exe $CFLAGS -mcpu="baseline" -O ReleaseFast --zig-lib-dir "$PWD/.zig/zig/lib" "$(SRC)"
    - name: Pack output
      run: |
        mv zig-out nightly
        7z a baseline_fast.7z nightly/bin/flow
        tar -cJf baseline_fast.tar.xz nightly/bin/flow
        tar -cf baseline_fast.tar nightly/bin/flow
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        make_latest: true
        files: |
          x1c_fast.tar
          x1c_fast.tar.xz
          x1c_fast.7z
    - name: Check zig binary size
      run: |
        ls -lh nightly/bin/
        ls -l nightly/bin/
        
  baseline_Small:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup llvm
      run: |
        curl -o llvm.sh https://apt.llvm.org/llvm.sh
        sudo chmod 777 llvm.sh
        sudo ./llvm.sh 19 all
    - name: Build
      run: |
        mkdir .zig && cd .zig
        curl -o zig.tar.xz $LINK
        tar -xf zig.tar.xz && rm zig.tar.xz
        mv * zig && cd zig && export PATH=$PATH:$PWD
        cd ../..
        zig build-exe $CFLAGS -mcpu="baseline" -O ReleaseSmall --zig-lib-dir "$PWD/.zig/zig/lib" "$(SRC)"
    - name: Pack output
      run: |
        mv zig-out nightly
        7z a baseline_small.7z nightly/bin/flow
        tar -cJf baseline_small.tar.xz nightly/bin/flow
        tar -cf baseline_small.tar nightly/bin/flow
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        make_latest: true
        files: |
          baseline_small.tar
          baseline_small.tar.xz
          baseline_small.7z
    - name: Check zig binary size
      run: |
        ls -lh nightly/bin/
        ls -l nightly/bin/
